name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_ACCESS }}

      - name: Deploying to Server
        run: |
          ssh -o StrictHostKeyChecking=no lucifer@prody.istenith.com << EOF
            cd prody-frontend
            git config pull.rebase false
            git pull origin master
            npm run build
            sudo systemctl restart prody-frontend.service
          EOF
