name: deploy frontend

on:
  push:
    branches:
      - master

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_ACCESS }}

      - name: Deploying to Server
        run: |
          ssh -o StrictHostKeyChecking=no lucifer@sumitdhiman.in << EOF
            cd prody-frontend
            git config pull.rebase false
            git pull origin master
            rm -rf node_modules
            yarn install
            yarn run build
            yarn run start & disown
          EOF
